openapi: 3.0.0
info:
  contact:
    name: nodejs-todo
  title: nodejs-todo
  description: |
    ## レポジトリ
    BE | [API](https://github.com/kazukinakama/nodejs-todo)
  version: 1.0.0
servers:
  - url: http://localhost:80/api
    description: local
tags:
  - name: Todos
    description: やること
paths:
  /todos:
    get:
      tags:
        - Todos
      responses:
        '200':
          $ref: '#/components/responses/GetTodosResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      operationId: getTodos
      description: 'getTodos'
    post:
      tags:
        - Todos
      responses:
        '200':
          $ref: '#/components/responses/CreateTodoResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      operationId: postTodo
      description: 'postTodo'
      requestBody:
        $ref: '#/components/requestBodies/CreateTodoRequest'
  /todos/{todo_id}:
    get:
      tags:
        - Todos
      responses:
        '200':
          $ref: '#/components/responses/GetTodoResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      operationId: getTodo
      description: 'getTodo'
      parameters:
        - in: path
          name: todo_id
          schema:
            type: integer
          required: true
    put:
      tags:
        - Todos
      responses:
        '200':
          $ref: '#/components/responses/UpdateTodoResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      operationId: putTodo
      description: 'putTodo'
      requestBody:
        $ref: '#/components/requestBodies/UpdateTodoRequest'
      parameters:
        - in: path
          name: todo_id
          schema:
            type: integer
          required: true
    delete:
      tags:
        - Todos
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      operationId: deleteTodo
      description: 'deleteTodo'
      parameters:
        - in: path
          name: todo_id
          schema:
            type: integer
          required: true
components:
  requestBodies:
    CreateTodoRequest:
      content:
        application/json:
          schema:
            $ref: ./requests/CreateTodoRequest.yml
    UpdateTodoRequest:
      content:
        application/json:
          schema:
            $ref: ./requests/UpdateTodoRequest.yml

  responses:
    GetTodosResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: ./responses/GetTodosResponse.yml
    GetTodoResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: ./responses/GetTodoResponse.yml
    CreateTodoResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: ./responses/CreateTodoResponse.yml
    UpdateTodoResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: ./responses/UpdateTodoResponse.yml
    ErrorResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: ./responses/ErrorResponse.yml
